import React from "react";
import WelcomeCollection from "./WelcomeCollection";

export default function Welcome() {
  return (
    <section className="welcome">
      <div className="auto__container">
        <h2>
          Welcome to
          <br />
          <span>FlyBoy</span>
        </h2>
        <div className="welcome__inner">
          <div className="welcome__inner-content">
            <p>
              FlyBoy is a collection of 5,150 unique NFTs randomly stored on the
              Ethereum blockchain. Each bear is algorithmically generated by
              combining various traits. Your FlyBoy doubles as your access to
              the FlyBoys’ Flying Club (FBFC), joining a family of NFT lovers
              who are avid travellers and aviators. FlyBoy is much more than just an avatar. 
              Physical and Virtual
              utilities have been planned, with the first physical utility being
              a personalised aviation tag of your own, from the famous
              Aviationtag.com. 
            </p>
          </div>
          <WelcomeCollection />
        </div>
      </div>
    </section>
  );
}
