import React, { Component } from "react";
import Slider from "react-slick";
function RoadPrev(props) {
  const { onClick } = props;
  return (
    <button type="button" className="roadPrev" onClick={onClick}>
      <img src="images/icons/chevron-left.svg" alt="" />
    </button>
  );
}
function RoadNext(props) {
  const { onClick } = props;
  return (
    <button type="button" className="roadNext" onClick={onClick}>
      <img src="images/icons/chevron-right.svg" alt="" />
    </button>
  );
}
export default class RoadmapSlider extends Component {
  render() {
    const settings = {
      slidesToShow: 3,
      infinite: false,
      nextArrow: <RoadNext />,
      prevArrow: <RoadPrev />,
      responsive: [
        {
          breakpoint: 1340,
          settings: {
            slidesToShow: 2,
          },
        },
        {
          breakpoint: 900,
          settings: {
            slidesToShow: 1,
          },
        },
      ],
    };

    return (
      <div className="roadmapSlider__outer">
        <div className="roadmapSlider">
          <Slider {...settings}>
            <div className="roadmapSlider__item">
              <div className="roadmapSlider__item-plane">
                <img src="images/plane/plane-brown.svg" alt="" />
              </div>
              <div className="roadmapSlider__item-index brown">01</div>
              <h5>Pre-Launch</h5>
              <p>
                Our top priority is to keep our NFT design quality worthy of our
                names. Each bear is algorithmically generated by combining
                100-150 traits.
                <br />
                <br /> Discord, instagram, Twitter and Official website launch.
                We will run various airdrop and whitelisting campaigns across
                the platforms to gain as much exposure as possible.
              </p>
            </div>
            <div className="roadmapSlider__item">
              <div className="roadmapSlider__item-plane">
                <img src="images/plane/plane-light.svg" alt="" />
              </div>
              <div className="roadmapSlider__item-index yellow">02</div>
              <h5>15% & 25% Sold Out</h5>
              <p>
                At 15%, we make a donation of $50,000 to the Royal Flying
                Doctor Service.
                <br />
                <br /> At 25%, we purchase land plots from Sandbox and
                Decentraland to expand the FlyBoys’ Flying Club (FBFC). Plus, a
                quarter of the royalty received from the project will be spent
                on buying more land plots in the future. All land plots will be
                kept at the FlyBoy Official Vault (the Vault). Any future
                proceeds from selling or renting out the land plots will be
                evenly distributed to our members.
              </p>
            </div>
            <div className="roadmapSlider__item">
              <div className="roadmapSlider__item-plane">
                <img src="images/plane/plane-blue.svg" alt="" />
              </div>
              <div className="roadmapSlider__item-index green">03</div>
              <h5>50% & 75% Sold Out</h5>
              <p>
                At 50%, we list our project on Rarity.tools. Also, we will
                launch our own launchpad and launch-fund worth dollars. This is to support members to launch their own NFT
                projects. We will provide fundings and expertise to support one
                of our own. FBFC is DAO (decentralised autonomous organization),
                all fundings applications will be decided collectively by the
                members.
                <br />
                <br /> At 75%, we will do a free merch drop to all members! Our
                first physical utility is a personalized aviation tag of your
                own, from the famous Aviationtag.com!
              </p>
            </div>
            <div className="roadmapSlider__item">
              <div className="roadmapSlider__item-plane">
                <img src="images/plane/plane-brown.svg" alt="" />
              </div>
              <div className="roadmapSlider__item-index brown">04</div>
              <h5>100% Sold Out</h5>
              <p>
                At 100%, we will announce our first airdrop, and the details of
                the first community event.
                <br />
                <br /> We will also announce our future plan for staking,
                metaverse integration, and Gamfi.
              </p>
            </div>
            <div className="roadmapSlider__item">
              <div className="roadmapSlider__item-plane">
                <img src="images/plane/plane-brown.svg" alt="" />
              </div>
              <div className="roadmapSlider__item-index yellow">05</div>
              <h5>Post-Launch</h5>
              <p>
                We want you all to be proud of being a FlyBoy owner. In the end,
                FlyBoy is about creating an exclusive community where members
                will support each other and are equal in status. FBFC is DAO,
                the future of the FlyBoys will be a collective decision of all
                members. All major decisions will be voted by our members and
                then executed.
                <br />
                <br />
                Once the project is sold out at 25%, we will buy more land plots
                in Sandbox and Decentraland. Members will be able to borrow one
                of our houses to host their own events. Any future proceeds from
                selling or renting out the houses will be shared equally with
                the members.
              </p>
            </div>
          </Slider>
        </div>
      </div>
    );
  }
}
